Chat ID.

diff --git a/telebash b/telebash
--- a/telebash
+++ b/telebash
@@ -1,8 +1,6 @@
 #!/bin/bash
 ## Send messages/documents with your Telegram bot.
-
-## TODO:
-## - Sort json output correctly when updating.
+## Check telegram-cli if you want more advanced features.
 
 RESET_COLOR="\e[0m"
 GREY="\e[37m"
@@ -11,62 +9,56 @@ GREEN="\e[32m"
 CYAN="\e[36m"
 RED="\e[31m"
 BOLD="\e[1m"
+UNDERLINE="\e[4m"
+ITALIC="\e[3m"
 
-TELEBASH_PATH="${HOME}/.telebash" ## << Change this
-TOKEN_CONFIG="${TELEBASH_PATH}/config/telegram_token.txt"
+TELEBASH_PATH="${HOME}/.config/telebash"
+TELEGRAM_TOKEN="${TELEBASH_PATH}/telegram_token.txt"
+TELEBASH_LOGO="${TELEBASH_PATH}/logo.txt"
 
-if [[ -f ${TOKEN_CONFIG} ]]
+if [[ -f ${TELEGRAM_TOKEN} ]]
 	then
-		source ${TELEBASH_PATH}/config/telegram_token.txt
+		source ${TELEGRAM_TOKEN}
 		[[ ${TELEGRAM_TOKEN} == "" ]] && echo -e "\n${RED}${BOLD} Token${RESET_COLOR}${RED} config file found but contain nothing!\n Exiting...${RESET_COLOR}\n"
 	else
 		echo -e "\n${RED} Token is missing!${RESET_COLOR}\n Get one with ${CYAN}${BOLD}@botfather${RESET_COLOR} on Telegram.\n" && exit 1
 fi
 
-CHAT_CONFIG="config/telegram_chat-id.txt"
-CHAT_CONFIG="${TELEBASH_PATH}/config/telegram_chat-id.txt"
-
-if [[ -f ${CHAT_CONFIG} ]]
-	then
-		source ${TELEBASH_PATH}/config/telegram_chat-id.txt
-		[[ ${TELEGRAM_CHAT_ID} == "" ]] && echo -e "\n${RED}${BOLD} Chat${RESET_COLOR}${RED} config file found but contain nothing!\n Exiting...${RESET_COLOR}\n" && exit 1
-	else
-		echo -e "\n${RED} Chat ID is missing!${RESET_COLOR}\n Get one with: 'curl -s https://api.telegram.org/bot<bot key>/getUpdates'\n"
-		exit 1
-fi
-
-TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_TOKEN}"
-
 function DISPLAY_HELP()
 {
-	echo -e "\n"
-	[[ -f ${TELEBASH_PATH}/config/logo.txt ]] && cat ${TELEBASH_PATH}/config/logo.txt
-	echo -e "${GREY}${BOLD}  Send messages/documents with your Telegram bot.\n${RESET_COLOR}"
-	echo -e " Usage:"
-	echo -e "	${YELLOW}${BOLD}-c${RESET_COLOR},${YELLOW}${BOLD}  --command${RESET_COLOR}      <command>           (Telegram can't handle large command output)."
-	echo -e "	${YELLOW}${BOLD}-h${RESET_COLOR},${YELLOW}${BOLD}  --help${RESET_COLOR}                             Display this help."
-	echo -e "	${YELLOW}${BOLD}-u${RESET_COLOR},${YELLOW}${BOLD}  --update${RESET_COLOR}                           Get the latest infos (groups, messages...)."
-	echo -e "	${YELLOW}${BOLD}-t${RESET_COLOR},${YELLOW}${BOLD}  --text${RESET_COLOR}         <text>"
-	echo -e "	${YELLOW}${BOLD}-u${RESET_COLOR},${YELLOW}${BOLD}  --url${RESET_COLOR}          <URL to document>\n"
+	[[ -f ${TELEBASH_LOGO} ]] && cat ${TELEBASH_LOGO}
+	echo -e " ${ITALIC}${CYAN}Send messages/documents with your Telegram bot.\n${RESET_COLOR}"
+	echo -e " ${UNDERLINE}${BOLD}Usage:${RESET_COLOR}"
+	echo -e "  ./telebash <options> <chat ID> <command/file/url/text>\n"
+	echo -e "  To get a chat ID, run this script with the '-u' flag.\n"
+	echo -e " ${UNDERLINE}${BOLD}Options:${RESET_COLOR}"
+	echo -e "  ${YELLOW}${BOLD}-c${RESET_COLOR},${YELLOW}${BOLD}	--command${RESET_COLOR}		<command>			(Telegram can't handle large command output)."
+	echo -e "  ${YELLOW}${BOLD}-d${RESET_COLOR},${YELLOW}${BOLD}	--doc${RESET_COLOR}			<path/URL to document>"
+	echo -e "  ${YELLOW}${BOLD}-h${RESET_COLOR},${YELLOW}${BOLD}	--help${RESET_COLOR}							Display this help."
+	echo -e "  ${YELLOW}${BOLD}-u${RESET_COLOR},${YELLOW}${BOLD}	--update${RESET_COLOR}						Get the latest infos (groups, messages...)."
+	echo -e "  ${YELLOW}${BOLD}-t${RESET_COLOR},${YELLOW}${BOLD}	--text${RESET_COLOR}			<text>\n"
 }
+
+TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_TOKEN}"
+TELEGRAM_CHAT_ID="${2}"
 
 function SEND_MESSAGE()
 {
 	ENDPOINT="sendMessage"
 	PARSE_MODE="markdown" ## "html" or "markdown"
-	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${TEXT}" ${TELEGRAM_API}/${ENDPOINT} > /dev/null
+	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${TEXT}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
 function SEND_COMMAND_OUTPUT()
 {
 	ENDPOINT="sendMessage"
-	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${COMMAND}" ${TELEGRAM_API}/${ENDPOINT} > /dev/null
+	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${COMMAND}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
 function SEND_DOCUMENT()
 {
 	ENDPOINT="sendDocument"
-	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&document=${DOCUMENT_URL}" ${TELEGRAM_API}/${ENDPOINT} > /dev/null
+	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&document=${DOCUMENT_URL}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
 function GET_UPDATE()
@@ -76,24 +68,25 @@ function GET_UPDATE()
 }
 
 REQUIREMENTS="curl jq"
+
 which ${REQUIREMENTS} > /dev/null
 
 if [[ ${?} -eq "0" ]]
 	then
 		case ${1} in
 			-c|--command)
-				COMMAND=$(${2})
+				COMMAND=$(${3})
 				SEND_COMMAND_OUTPUT
 				;;
 			-d|--doc)
-				DOCUMENT_URL="${2}"
+				DOCUMENT_URL="${3}"
 				SEND_DOCUMENT
 				;;
 			-h| --help)
 				DISPLAY_HELP
 				;;
 			-t|--text)
-				TEXT="${2}"
+				TEXT="${3}"
 				SEND_MESSAGE
 				;;
 			-u| --update)
@@ -105,5 +98,5 @@ if [[ ${?} -eq "0" ]]
 		esac
 	else
 		echo -e "${RED}\n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RESET_COLOR}\n${RED} Exiting...${RESET_COLOR}\n"
-		exit 0
+		exit 1
 fi
