Minor changes.

diff --git a/telebash b/telebash
--- a/telebash
+++ b/telebash
@@ -2,7 +2,7 @@
 ## Send messages/documents with your Telegram bot.
 ## Check telegram-cli if you want more advanced features.
 
-RESET_COLOR="\e[0m"
+RC="\e[0m"
 GREY="\e[37m"
 YELLOW="\e[33m"
 GREEN="\e[32m"
@@ -19,49 +19,49 @@ TELEBASH_LOGO="${TELEBASH_PATH}/logo.txt"
 if [[ -f ${TELEGRAM_TOKEN} ]]
 	then
 		source ${TELEGRAM_TOKEN}
-		[[ ${TELEGRAM_TOKEN} == "" ]] && echo -e "\n${RED}${BOLD} Token${RESET_COLOR}${RED} config file found but contain nothing!\n Exiting...${RESET_COLOR}\n"
+		[[ ${TELEGRAM_TOKEN} == "" ]] && echo -e "\n${RED}${BOLD} Token${RC}${RED} config file found but contain nothing!\n Exiting...${RC}\n"
 	else
-		echo -e "\n${RED} Token is missing!${RESET_COLOR}\n Get one with ${CYAN}${BOLD}@botfather${RESET_COLOR} on Telegram.\n" && exit 1
+		echo -e "\n${RED} Token is missing!${RC}\n Get one with ${CYAN}${BOLD}@botfather${RC} on Telegram.\n" && exit 1
 fi
 
-function DISPLAY_HELP()
+DISPLAY_HELP()
 {
 	[[ -f ${TELEBASH_LOGO} ]] && cat ${TELEBASH_LOGO}
-	echo -e " ${ITALIC}${CYAN}Send messages/documents with your Telegram bot.\n${RESET_COLOR}"
-	echo -e " ${UNDERLINE}${BOLD}Usage:${RESET_COLOR}"
-	echo -e "  ./telebash <options> <chat ID> <command/file/url/text>\n"
+	echo -e " ${ITALIC}${CYAN}Send messages/documents with your Telegram bot.\n${RC}"
+	echo -e " ${UNDERLINE}${BOLD}Usage:${RC}"
+	echo -e "  ./telebash ${GREY}<${RC}options${GREY}> <${RC}chat ID${GREY}> <${RC}command/file/url/text${GREY}>${RC}\n"
 	echo -e "  To get a chat ID, run this script with the '-u' flag.\n"
-	echo -e " ${UNDERLINE}${BOLD}Options:${RESET_COLOR}"
-	echo -e "  ${YELLOW}${BOLD}-c${RESET_COLOR},${YELLOW}${BOLD}	--command${RESET_COLOR}		<command>			(Telegram can't handle large command output)."
-	echo -e "  ${YELLOW}${BOLD}-d${RESET_COLOR},${YELLOW}${BOLD}	--doc${RESET_COLOR}			<URL to document>		Send a files on the internet."
-	echo -e "  ${YELLOW}${BOLD}-h${RESET_COLOR},${YELLOW}${BOLD}	--help${RESET_COLOR}							Display this help."
-	echo -e "  ${YELLOW}${BOLD}-u${RESET_COLOR},${YELLOW}${BOLD}	--update${RESET_COLOR}						Get the latest infos (groups, messages...)."
-	echo -e "  ${YELLOW}${BOLD}-t${RESET_COLOR},${YELLOW}${BOLD}	--text${RESET_COLOR}			<text>				Send a text message.\n"
+	echo -e " ${UNDERLINE}${BOLD}Options:${RC}"
+	echo -e "  ${YELLOW}${BOLD}-c${RC},${YELLOW}${BOLD}	--command${RC}		<command>			(Telegram can't handle large command output)."
+	echo -e "  ${YELLOW}${BOLD}-d${RC},${YELLOW}${BOLD}	--doc${RC}			<URL to document>		Send a files on the internet."
+	echo -e "  ${YELLOW}${BOLD}-h${RC},${YELLOW}${BOLD}	--help${RC}							Display this help."
+	echo -e "  ${YELLOW}${BOLD}-u${RC},${YELLOW}${BOLD}	--update${RC}						Get the latest infos (groups, messages...)."
+	echo -e "  ${YELLOW}${BOLD}-t${RC},${YELLOW}${BOLD}	--text${RC}			<text>				Send a text message.\n"
 }
 
 TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_TOKEN}"
 TELEGRAM_CHAT_ID="${2}"
 
-function SEND_MESSAGE()
+SEND_MESSAGE()
 {
 	ENDPOINT="sendMessage"
 	PARSE_MODE="markdown" ## "html" or "markdown"
 	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${TEXT}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
-function SEND_COMMAND_OUTPUT()
+SEND_COMMAND_OUTPUT()
 {
 	ENDPOINT="sendMessage"
 	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&parse_mode=${PARSE_MODE}&text=${COMMAND}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
-function SEND_DOCUMENT()
+SEND_DOCUMENT()
 {
 	ENDPOINT="sendDocument"
 	curl -s -d "chat_id=${TELEGRAM_CHAT_ID}&document=${DOCUMENT_URL}" ${TELEGRAM_API}/${ENDPOINT} | jq
 }
 
-function GET_UPDATE()
+GET_UPDATE()
 
 {
 	curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getUpdates" | jq
@@ -97,6 +97,6 @@ if [[ ${?} -eq "0" ]]
 				;;
 		esac
 	else
-		echo -e "${RED}\n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RESET_COLOR}\n${RED} Exiting...${RESET_COLOR}\n"
+		echo -e "${RED}\n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RC}\n${RED} Exiting...${RC}\n"
 		exit 1
 fi
