Tab

diff --git a/telebash b/telebash
--- a/telebash
+++ b/telebash
@@ -21,115 +21,115 @@ TELEGRAM_CHAT_ID="${3}"
 
 DISPLAY_HELP()
 {
-	echo -e " \n${UL}Usage:${RC}"
-	echo -e "  ./telebash <options> <text/command> <chat ID>\n"
-	echo -e "  To get a chat ID, run this script with '-u'.\n"
-	echo -e " ${UL}Options:${RC}"
-	echo -e "  ${YELLOW}-c,	--command${RC}	<command>	Send a command output.${RC}"
-	echo -e "  ${YELLOW}-d,	--document${RC}	<path>		Send a document.${RC}"
-	echo -e "  ${YELLOW}-h,	--help${RC}				Display this help.${RC}"
-	echo -e "  ${YELLOW}-t,	--text${RC}		<text>		Send a text message.${RC}"
-	echo -e "  ${YELLOW}-u,	--update${RC}			Get the latest infos (groups, messages...)${RC}\n"
+    echo -e " \n${UL}Usage:${RC}"
+    echo -e "  ./telebash <options> <text/command> <chat ID>\n"
+    echo -e "  To get a chat ID, run this script with '-u'.\n"
+    echo -e " ${UL}Options:${RC}"
+    echo -e "  ${YELLOW}-c,    --command${RC}    <command>    Send a command output.${RC}"
+    echo -e "  ${YELLOW}-d,    --document${RC}    <path>        Send a document.${RC}"
+    echo -e "  ${YELLOW}-h,    --help${RC}                Display this help.${RC}"
+    echo -e "  ${YELLOW}-t,    --text${RC}        <text>        Send a text message.${RC}"
+    echo -e "  ${YELLOW}-u,    --update${RC}            Get the latest infos (groups, messages...)${RC}\n"
 }
 
 SEND_MESSAGE()
 {
-	ENDPOINT="sendMessage"
-	PARSE_MODE="html" ## "html" or "markdown"
+    ENDPOINT="sendMessage"
+    PARSE_MODE="html" ## "html" or "markdown"
 
-	curl \
-		--silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
-		--form chat_id="${TELEGRAM_CHAT_ID}"\
-		--form parse_mode="${PARSE_MODE}" \
-		--form text="${TEXT}" \
-		| jq
+    curl \
+        --silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
+        --form chat_id="${TELEGRAM_CHAT_ID}"\
+        --form parse_mode="${PARSE_MODE}" \
+        --form text="${TEXT}" \
+        | jq
 }
 
 SEND_DOCUMENT()
 {
-	ENDPOINT="sendDocument"
+    ENDPOINT="sendDocument"
 
-	curl \
-		--silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
-		--form document=@${DOCUMENT} \
-		--form chat_id="${TELEGRAM_CHAT_ID}"\
-		| jq
+    curl \
+        --silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
+        --form document=@${DOCUMENT} \
+        --form chat_id="${TELEGRAM_CHAT_ID}"\
+        | jq
 }
 
 GET_UPDATE()
 {
-	ENDPOINT="getUpdates"
+    ENDPOINT="getUpdates"
 
-	curl \
-		--silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
-		| jq
+    curl \
+        --silent "${TELEGRAM_API_URL}${TELEGRAM_TOKEN}/${ENDPOINT}" \
+        | jq
 }
 
 REQUIREMENTS="curl jq"
 
 if ! which ${REQUIREMENTS} > /dev/null
-	then
-		echo -e "${RED} \n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RC}\n"
-		exit 1
-	else
-		if [[ ! -f ${TELEGRAM_TOKEN_FILE} || ! ${TELEGRAM_TOKEN} ]]
-			then
-				echo -e "\n ${RED}Token is missing!\n ${RC} \n Get one with ${CYAN}@botfather${RC} on Telegram.\n"
-				exit 1
-		fi
+    then
+        echo -e "${RED} \n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RC}\n"
+        exit 1
+    else
+        if [[ ! -f ${TELEGRAM_TOKEN_FILE} || ! ${TELEGRAM_TOKEN} ]]
+            then
+                echo -e "\n ${RED}Token is missing!\n ${RC} \n Get one with ${CYAN}@botfather${RC} on Telegram.\n"
+                exit 1
+        fi
 
 
-		case ${1} in
-			-c|--command)
-				TEXT=$(${2})
-				if SEND_MESSAGE
-					then
-						echo -e "${GREEN}Message sent.${RC}"
-					else
-						echo -e "${RED}Something went wrong!${RC}"
-						exit 1
-				fi
-				;;
+        case ${1} in
+            -c|--command)
+                TEXT=$(${2})
+                if SEND_MESSAGE
+                    then
+                        echo -e "${GREEN}Message sent.${RC}"
+                    else
+                        echo -e "${RED}Something went wrong!${RC}"
+                        exit 1
+                fi
+                ;;
 
-			-d|--document)
-				DOCUMENT=${2}
-				if SEND_DOCUMENT
-					then
-						echo -e "${GREEN}Message sent.${RC}"
-					else
-						echo -e "${RED}Something went wrong!${RC}"
-						exit 1
-				fi
-				;;
+            -d|--document)
+                DOCUMENT=${2}
+                if SEND_DOCUMENT
+                    then
+                        echo -e "${GREEN}Message sent.${RC}"
+                    else
+                        echo -e "${RED}Something went wrong!${RC}"
+                        exit 1
+                fi
+                ;;
 
-			-h| --help)
-				DISPLAY_HELP
-				;;
+            -h| --help)
+                DISPLAY_HELP
+                ;;
 
-			-t|--text)
-				TEXT=${2}
-				if SEND_MESSAGE
-					then
-						echo -e "${GREEN}Message sent.${RC}"
-					else
-						echo -e "${RED}Something went wrong!${RC}"
-						exit 1
-				fi
-				;;
+            -t|--text)
+                TEXT=${2}
+                if SEND_MESSAGE
+                    then
+                        echo -e "${GREEN}Message sent.${RC}"
+                    else
+                        echo -e "${RED}Something went wrong!${RC}"
+                        exit 1
+                fi
+                ;;
 
-			-u|--update)
-				if GET_UPDATE
-					then
-						echo -e "${GREEN}Done.${RC}"
-					else
-						echo -e "${RED}Something went wrong!${RC}"
-						exit 1
-				fi
-				;;
+            -u|--update)
+                if GET_UPDATE
+                    then
+                        echo -e "${GREEN}Done.${RC}"
+                    else
+                        echo -e "${RED}Something went wrong!${RC}"
+                        exit 1
+                fi
+                ;;
 
-			*)
-				DISPLAY_HELP
-				;;
+            *)
+                DISPLAY_HELP
+                ;;
 
-		esac
+        esac
 fi
